<a href="https://colab.research.google.com/github/Chaliantosh/datascience_cheatsheets/blob/main/Decision_tree.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import sys
import sklearn

In [14]:
#It is used for binary classification and multi class classification
from sklearn import tree

In [2]:
X = [[0,0], [1,2]]
y = [0, 1]

In [7]:
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X, y)

In [8]:
clf.predict([[2., 2.]])

array([1])

In [9]:
clf.predict_proba([[2., 2.]])

array([[0., 1.]])

In [10]:
clf.predict([[0.4, 1.2]])

array([1])

In [11]:
clf.predict_proba([[0.4, 1.2]])

array([[0., 1.]])

In [12]:
clf.predict_proba([[0, 0.2]])

array([[1., 0.]])