<a href="https://colab.research.google.com/github/Chaliantosh/datascience_cheatsheets/blob/main/NN_%26_DL_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np
a = np.array([[1,2],[3,4]])
b = np.array([[5,6,7],[8,9,10]])
c = np.array([[5,6],[8,9]])
print('matrix a dimension', a.shape)
print('matrix b dimension', b.shape)
print('matrix c dimension', c.shape)

matrix a dimension (2, 2)
matrix b dimension (2, 3)
matrix c dimension (2, 2)


In [6]:
#cross product
c = np.dot(a,b)
print('dot product of a & b:', c)
print('matrix c dimension', c.shape)

dot product of a & b: [[21 24 27]
 [47 54 61]]
matrix c dimension (2, 3)


In [10]:
#element wise multiplication
d = np.multiply(a,c)
print('element wise product of a & b:', d)
print('matrix c dimension', d.shape)

element wise product of a & b: [[ 5 12]
 [24 36]]
matrix c dimension (2, 2)


In [12]:
#Broadcasting 1: Addition of a matrix and a row vector
a = np.array([[10, 10, 10], [20, 20, 20], [30, 30, 30]])
b = np.array([1, 2, 3])
c = a*b
print(c)

[[10 20 30]
 [20 40 60]
 [30 60 90]]


In [13]:
#Broadcasting 2: Addition of a matrix and a scalar
a = np.array([[10, 10, 10], [20, 20, 20], [30, 30, 30]])
b = 1
c = a + b
print(c)

[[11 11 11]
 [21 21 21]
 [31 31 31]]


In [15]:
#Broadcasting 3: element wise function call
def exp(x, n):
  return x**n

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(exp(a, 2))

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [21]:
#calories from carbs, proteins, fats in 100g of different foods:
#            Apples    Beef      Eggs    Potatoes
#    carb    56.0       0.0      4.4       68.0
#proteins     1.2     104.0     52.0        8.0
#     Fat     1.8     135.0     99.0        0.9
import numpy as np
A = np.array([[56.0,   0.0,  4.4, 68.0],
              [1.2, 104.0, 52.0,  8.0],
              [1.8, 135.0, 99.0,  0.9]])
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [24]:
cal = A.sum(axis=0)
print(cal)
percentage = 100*A/cal.reshape(1,4)
print(percentage)

[ 59.  239.  155.4  76.9]
[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]
