In [4]:
import numpy as np #numpy is used for array imputation

In [8]:
#creating an array
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [9]:
#multiplying the array
arr*arr

array([1, 4, 9])

In [11]:
v1=np.random.rand(1000000)
v2=np.random.rand(1000000)
%time v1*v2

Wall time: 11 ms
Compiler : 1.4 s


array([0.00685364, 0.32139908, 0.33247152, ..., 0.03192234, 0.18841501,
       0.48273082])

observations: numpy is very fast it computed million random array multiplication in 11ms.

In [13]:
#dot product of an array
np.dot(arr, arr)

14

In [18]:
#creating 3*3 matrix
mat = np.array([[1,2,3], [4,5,6], [7,8,9]])
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
#using arange method to create an array
v=np.arange(0,12)
v

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [21]:
#using reshape method to create rows & columns
v.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [25]:
#combining arange and reshape methods
v=np.arange(0,12).reshape(4,3)
v

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [24]:
#display rows and columns of an array
v.shape

(4, 3)

In [26]:
#changing the array value
v[1,2] = 17
v

array([[ 0,  1,  2],
       [ 3,  4, 17],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [28]:
#transpose of a matrix
v.transpose()

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2, 17,  8, 11]])

# Slicing: to select subsets of data

In [31]:
v=np.arange(1,6)
v[2:4]

array([3, 4])

In [33]:
arr=np.arange(12).reshape(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [34]:
#slice out first row
arr[0]

array([0, 1, 2, 3])

In [37]:
#slice out second row and second column
arr[1,1]

5

In [40]:
#all the elements of second column in a row
arr[:,1]

array([1, 5, 9])

In [41]:
#all the elements of second column in a column format
arr[:,1].reshape(3,1)

array([[1],
       [5],
       [9]])

In [42]:
#slicing on both axis
arr[1:, 2:]

array([[ 6,  7],
       [10, 11]])

In [43]:
#scalar to the matrix
arr[1:, 2:] = 7
arr

array([[0, 1, 2, 3],
       [4, 5, 7, 7],
       [8, 9, 7, 7]])

# Boolean Indexing

In [45]:
arr=np.arange(3)
arr

array([0, 1, 2])

In [46]:
arr[np.array([True, False, True])]

array([0, 2])

In [47]:
arr >= 1

array([False,  True,  True])

In [48]:
arr[arr>=1]

array([1, 2])

In [49]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
arr[(arr>2) & (arr<7)]

array([3, 4, 5, 6])

In [51]:
arr[(arr>7) | (arr<2)]

array([0, 1, 8, 9])

In [52]:
arr[~(arr>7)]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [78]:
mat = np.random.rand(5,5)
mat

array([[0.69922338, 0.40915781, 0.55265502, 0.48237618, 0.52942924],
       [0.69387764, 0.45869699, 0.69829126, 0.86084492, 0.11889479],
       [0.64021762, 0.18262598, 0.81924447, 0.1779294 , 0.63896169],
       [0.78376843, 0.02442437, 0.88730158, 0.90533609, 0.83889532],
       [0.0856723 , 0.41335412, 0.92594261, 0.97030237, 0.52436029]])

In [79]:
mat[np.abs(mat-mat.mean()) > 1.5*mat.std()]

array([0.11889479, 0.02442437, 0.0856723 ])

In [80]:
#difference of each element from the mean
np.abs(mat-mat.mean())

array([[0.12635203, 0.16371354, 0.02021633, 0.09049518, 0.04344211],
       [0.12100628, 0.11417437, 0.12541991, 0.28797357, 0.45397657],
       [0.06734627, 0.39024537, 0.24637311, 0.39494195, 0.06609034],
       [0.21089708, 0.54844698, 0.31443022, 0.33246473, 0.26602396],
       [0.48719906, 0.15951723, 0.35307125, 0.39743101, 0.04851107]])

In [81]:
#elements where greater than 1.5 times of std()
np.abs(mat-mat.mean()) > 1.5*mat.std()

array([[False, False, False, False, False],
       [False, False, False, False,  True],
       [False, False, False, False, False],
       [False,  True, False, False, False],
       [ True, False, False, False, False]])

In [82]:
mat[np.abs(mat-mat.mean()) > 1.5*mat.std()]

array([0.11889479, 0.02442437, 0.0856723 ])

In [83]:
#these outliers can be normalized to the mean.
mat[np.abs(mat-mat.mean()) > 1.5*mat.std()] = mat.mean()

# Understand broadcasting

In [85]:
arr=np.arange(3)
arr

array([0, 1, 2])

In [89]:
#adding array to scalar
arr+4

array([4, 5, 6])

In [90]:
arr/7

array([0.        , 0.14285714, 0.28571429])

In [91]:
arr**2

array([0, 1, 4], dtype=int32)

In [93]:
#creating 3*3 matrix
mat=np.arange(9).reshape(3,3)
mat

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [95]:
#creating 1*3 matrix
vec=np.arange(3)
vec

array([0, 1, 2])

In [97]:
#adding matrix to a vector
mat + vec

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

In [100]:
#creating vector of 1 row and 3 columns
v1=np.arange(3)
v1

array([0, 1, 2])

In [101]:
#creating vector of 3 row and 1 columns
v2=np.arange(3).reshape(3,1)
v2

array([[0],
       [1],
       [2]])

In [103]:
#adding above two vectors
v1+v2

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [104]:
np.arange(3) + np.arange(4)

ValueError: operands could not be broadcast together with shapes (3,) (4,) 