In [2]:
import numpy as np #numpy is used for array imputation

In [3]:
#creating an array
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [4]:
#multiplying the array
arr*arr

array([1, 4, 9])

In [5]:
v1=np.random.rand(1000000)
v2=np.random.rand(1000000)
%time v1*v2

Wall time: 10 ms


array([0.00793987, 0.04123414, 0.10818446, ..., 0.25059428, 0.26761512,
       0.71946943])

observations: numpy is very fast it computed million random array multiplication in 11ms.

In [6]:
#dot product of an array
np.dot(arr, arr)

14

In [7]:
#creating 3*3 matrix
mat = np.array([[1,2,3], [4,5,6], [7,8,9]])
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
#using arange method to create an array
v=np.arange(0,12)
v

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [9]:
#using reshape method to create rows & columns
v.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [10]:
#combining arange and reshape methods
v=np.arange(0,12).reshape(4,3)
v

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [11]:
#display rows and columns of an array
v.shape

(4, 3)

In [12]:
#changing the array value
v[1,2] = 17
v

array([[ 0,  1,  2],
       [ 3,  4, 17],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [13]:
#transpose of a matrix
v.transpose()

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2, 17,  8, 11]])

# Slicing: to select subsets of data

In [14]:
v=np.arange(1,6)
v[2:4]

array([3, 4])

In [15]:
arr=np.arange(12).reshape(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [16]:
#slice out first row
arr[0]

array([0, 1, 2, 3])

In [17]:
#slice out second row and second column
arr[1,1]

5

In [18]:
#all the elements of second column in a row
arr[:,1]

array([1, 5, 9])

In [19]:
#all the elements of second column in a column format
arr[:,1].reshape(3,1)

array([[1],
       [5],
       [9]])

In [20]:
#slicing on both axis
arr[1:, 2:]

array([[ 6,  7],
       [10, 11]])

In [21]:
#scalar to the matrix
arr[1:, 2:] = 7
arr

array([[0, 1, 2, 3],
       [4, 5, 7, 7],
       [8, 9, 7, 7]])

# Boolean Indexing

In [22]:
arr=np.arange(3)
arr

array([0, 1, 2])

In [23]:
arr[np.array([True, False, True])]

array([0, 2])

In [24]:
arr >= 1

array([False,  True,  True])

In [25]:
arr[arr>=1]

array([1, 2])

In [26]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
arr[(arr>2) & (arr<7)]

array([3, 4, 5, 6])

In [28]:
arr[(arr>7) | (arr<2)]

array([0, 1, 8, 9])

In [29]:
arr[~(arr>7)]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [30]:
mat = np.random.rand(5,5)
mat

array([[0.92780598, 0.32094298, 0.42574874, 0.78071718, 0.10738382],
       [0.84919036, 0.11200464, 0.53099086, 0.50673998, 0.22709614],
       [0.59949608, 0.5103563 , 0.77730176, 0.41624643, 0.72202505],
       [0.2111021 , 0.31884609, 0.1505918 , 0.68934884, 0.79477144],
       [0.84288496, 0.47700148, 0.55925061, 0.36151251, 0.53984927]])

In [31]:
mat[np.abs(mat-mat.mean()) > 1.5*mat.std()]

array([0.92780598, 0.10738382, 0.11200464])

In [32]:
#difference of each element from the mean
np.abs(mat-mat.mean())

array([[4.17437762e-01, 1.89425234e-01, 8.46194757e-02, 2.70348960e-01,
        4.02984391e-01],
       [3.38822144e-01, 3.98363574e-01, 2.06226403e-02, 3.62823546e-03,
        2.83272078e-01],
       [8.91278681e-02, 1.19160950e-05, 2.66933543e-01, 9.41217905e-02,
        2.11656830e-01],
       [2.99266115e-01, 1.91522129e-01, 3.59776416e-01, 1.78980625e-01,
        2.84403228e-01],
       [3.32516745e-01, 3.33667392e-02, 4.88823971e-02, 1.48855707e-01,
        2.94810575e-02]])

In [33]:
#elements where greater than 1.5 times of std()
np.abs(mat-mat.mean()) > 1.5*mat.std()

array([[ True, False, False, False,  True],
       [False,  True, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [34]:
mat[np.abs(mat-mat.mean()) > 1.5*mat.std()]

array([0.92780598, 0.10738382, 0.11200464])

In [35]:
#these outliers can be normalized to the mean.
mat[np.abs(mat-mat.mean()) > 1.5*mat.std()] = mat.mean()

# Understand broadcasting

In [36]:
arr=np.arange(3)
arr

array([0, 1, 2])

In [37]:
#adding array to scalar
arr+4

array([4, 5, 6])

In [38]:
arr/7

array([0.        , 0.14285714, 0.28571429])

In [39]:
arr**2

array([0, 1, 4], dtype=int32)

In [40]:
#creating 3*3 matrix
mat=np.arange(9).reshape(3,3)
mat

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [41]:
#creating 1*3 matrix
vec=np.arange(3)
vec

array([0, 1, 2])

In [42]:
#adding matrix to a vector
mat + vec

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

In [43]:
#creating vector of 1 row and 3 columns
v1=np.arange(3)
v1

array([0, 1, 2])

In [44]:
#creating vector of 3 row and 1 columns
v2=np.arange(3).reshape(3,1)
v2

array([[0],
       [1],
       [2]])

In [45]:
#adding above two vectors
v1+v2

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [46]:
np.arange(3) + np.arange(4)

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

# Understand array Operations

In [55]:
v=np.arange(12).reshape(4,3)
v

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [49]:
#attributes of vector v can be listed by following method.
dir(v)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

In [51]:
#v.any() will return true if atleaset one element is true.
v.any()

True

In [52]:
#v.all() eill return true if all the values are true
v.all()

False

In [53]:
#since python can't guess whether it is any() or all(), the error is being thrown.
if v:
    print('v is true')

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [54]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


In [56]:
#to get sum of each row
v.sum(axis=1)

array([ 3, 12, 21, 30])

In [58]:
#to get sum of each column
v.sum(axis=0)

array([18, 22, 26])

In [64]:
v1=v.copy
v

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

# Understand ufuncs

In [65]:
v=np.arange(-3,3)
v

array([-3, -2, -1,  0,  1,  2])

In [66]:
def noneg(n):
    if n < 0:
        return 0
    return n

In [67]:
noneg(3)

3

In [68]:
noneg(-3)

0

In [69]:
noneg(v)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [70]:
#decorators are functions which uses functions as parameters and returns function.
@np.vectorize
def noneg(n):
    if n < 0:
        return 0
    return n

In [71]:
noneg(3)

array(3)

In [72]:
noneg(3).shape

()

In [73]:
noneg(v)

array([0, 0, 0, 0, 1, 2])