In [5]:
import numpy as np #numpy is used for array imputation

In [6]:
mydata=np.arange(0,20)
mydata

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [8]:
np.reshape(mydata,(5,4)) # 5 rows and 4 columns

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [10]:
np.reshape(mydata,(4,5)) # 4 rows and 5 columns

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [12]:
MATR1=np.reshape(mydata,(5,4),order='c') # reshape behaviours are C,F,A
MATR1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [19]:
a1=['welcome','to','datascience']
a2=['required','hard','work']
a3=[1,2,3]
arr = np.array([a1,a2,a3])
arr

array([['welcome', 'to', 'datascience'],
       ['required', 'hard', 'work'],
       ['1', '2', '3']], dtype='<U11')

In [22]:
li = [a1,a2,a3]
li

[['welcome', 'to', 'datascience'], ['required', 'hard', 'work'], [1, 2, 3]]

In [23]:
type(arr)

numpy.ndarray

In [24]:
type(li)

list